### ISSUE TITLE
[feat] Factory/helper functions

### ISSUE THREAD

**Issue by tadeubdev** [mattiasgeniar/php-percentages#6]
Hi! This project is cool!
It will be a good way if I create factories functions for these methods?
For example:

```php
percentage(10, 200)
percentage_between(10, 200)
percentage_abs_between(10, 200)
percentage_of(10, 200)
```

**Comment by mattiasgeniar** [comment]
Hey @tadeubarbosa, yes that would actually be really convenient!

**Comment by tadeubdev** [comment]
ok, I'll work in that!
